
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class Ajustes extends javax.swing.JFrame {

    /**
     * Creates new form Ajustes
     */
    private Ajustes() {
        initComponents();
        
        VValoracion=new Valoracion(this,true);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int posX = (pantalla.width - this.getWidth()) / 2;
        int posY = (pantalla.height - this.getHeight()) / 2;
        this.setLocation(posX, posY);
        
    }
    public Ajustes(Pintado Vpinta,Principal Vprin){
        this();
        this.Vpinta=Vpinta;
        this.Vprin=Vprin;
        
    }
    public void setEtiqueta(String t){
        jLabel1.setText(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PAjustes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BValorar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PAjustes.setBackground(new java.awt.Color(153, 204, 255));

        jButton1.setText("Borra Nombre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BValorar.setText("Valorar");
        BValorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValorarActionPerformed(evt);
            }
        });

        jLabel1.setText("----------");

        javax.swing.GroupLayout PAjustesLayout = new javax.swing.GroupLayout(PAjustes);
        PAjustes.setLayout(PAjustesLayout);
        PAjustesLayout.setHorizontalGroup(
            PAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAjustesLayout.createSequentialGroup()
                .addGroup(PAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAjustesLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton1))
                    .addGroup(PAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PAjustesLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PAjustesLayout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addComponent(BValorar))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        PAjustesLayout.setVerticalGroup(
            PAjustesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAjustesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BValorar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(PAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Vpinta.LUser1.setText(" ");
        Vprin.jUser.setText(" ");
        Vprin.jNombre.setText(" ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BValorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValorarActionPerformed
        // TODO add your handling code here:
        VValoracion.setVisible(true);
    }//GEN-LAST:event_BValorarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajustes().setVisible(true);
            }
        });
    }
    
    private Principal Vprin;
    private Pintado Vpinta;
    private Valoracion VValoracion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton BValorar;
    javax.swing.JPanel PAjustes;
    javax.swing.JButton jButton1;
    javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
