
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class Ajustes extends javax.swing.JFrame {

    /**
     * Creates new form Ajustes
     */
    private Ajustes() {
        initComponents();
        VValoracion=new Valoracion(this,true);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int posX = (pantalla.width - this.getWidth()) / 2;
        int posY = (pantalla.height - this.getHeight()) / 2;
        this.setLocation(posX, posY);
        
    }
    public Ajustes(Pintado Vpinta,Principal Vprin){
        this();
        this.Vpinta=Vpinta;
        this.Vprin=Vprin;
        
    }
    public void setEtiqueta(String t){
        jLabel1.setText(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PAjustes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        BValorar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CBDark = new javax.swing.JCheckBox();

        PAjustes.setBackground(new java.awt.Color(153, 204, 255));
        PAjustes.setLayout(new java.awt.GridLayout(5, 1, 0, 5));

        jButton1.setText("Borra Nombre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PAjustes.add(jButton1);

        BValorar.setText("Valorar");
        BValorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValorarActionPerformed(evt);
            }
        });
        PAjustes.add(BValorar);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("----------");
        PAjustes.add(jLabel1);

        CBDark.setText("Modo Oscuro");
        CBDark.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CBDarkStateChanged(evt);
            }
        });
        CBDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDarkActionPerformed(evt);
            }
        });
        PAjustes.add(CBDark);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Vpinta.LUser1.setText(" ");
        Vprin.jUser.setText(" ");
        Vprin.jNombre.setText(" ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BValorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValorarActionPerformed
        // TODO add your handling code here:
        VValoracion.setVisible(true);
    }//GEN-LAST:event_BValorarActionPerformed

    private void CBDarkStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CBDarkStateChanged
        // TODO add your handling code here:
        modoOscuro(CBDark.isSelected());
    }//GEN-LAST:event_CBDarkStateChanged

    private void CBDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBDarkActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajustes().setVisible(true);
            }
        });
    }
    private void modoOscuro(boolean cambiar) {
        Color nuevoColor = cambiar ? Color.DARK_GRAY : null;
        getContentPane().setBackground(nuevoColor);
        Vpinta.getContentPane().setBackground(nuevoColor);
        VValoracion.getContentPane().setBackground(nuevoColor);
        Vprin.getContentPane().setBackground(nuevoColor);
    }
    
    private Principal Vprin;
    private Pintado Vpinta;
    private Valoracion VValoracion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton BValorar;
    javax.swing.JCheckBox CBDark;
    javax.swing.JPanel PAjustes;
    javax.swing.JButton jButton1;
    javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
